---

  - name: reference nodesource on version 16
    shell: 'curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -'
    become: yes

  - name: Check GCP repo file exist
    stat:
      path: /etc/yum.repos.d/google-cloud.repo
    register: gcp_repo_exist
    become: yes

  - ansible.builtin.replace:
      path: /etc/yum.repos.d/google-cloud.repo
      regexp: 'repo_gpgcheck=1'
      replace: 'repo_gpgcheck=0'
    when: gcp_repo_exist.stat.exists == True
    become: yes

  - name: install nodejs from nodesource
    shell: 'yum install nodejs --enablerepo=nodesource -y'
    become: yes

  - name: install build essentials for native modules
    yum:
      name: gcc-c++
      state: present
    become: yes
